/* peter */
INSERT INTO CLIENT (CLIENT_ID, CLIENT_NAME, CLIENT_ADDRESS1, CLIENT_ADDRESS2, CLIENT_ADDRESS_CITY, CLIENT_ADDRESS_POST_CODE, CLIENT_COUNTRY)
VALUES (1, 'mB7gX/bCT4LJfIdiR4TidQ==', '3S1AM08muFcXQaZvuOV4dA==', 'suXXU1/uXHza95aulWkTXg==', 'yCpQBvSWPBWCLEu7rI2JGQ==', 'ZAt8nJXNWbz5+YRSsWDo1A==', 'H9he3wZ+a/sm1P38uvn9uw==');

/* paul */
INSERT INTO CLIENT (CLIENT_ID, CLIENT_NAME, CLIENT_ADDRESS1, CLIENT_ADDRESS2, CLIENT_ADDRESS_CITY, CLIENT_ADDRESS_POST_CODE, CLIENT_COUNTRY)
VALUES (2, 'mw8Z8oMHU565u29rr1/0AA==', '3S1AM08muFcXQaZvuOV4dA==', 'suXXU1/uXHza95aulWkTXg==', 'yCpQBvSWPBWCLEu7rI2JGQ==', 'ZAt8nJXNWbz5+YRSsWDo1A==', 'H9he3wZ+a/sm1P38uvn9uw==');

INSERT INTO PRODUCT_ITEM (PI_ID, PI_NAME, PI_QUANTITY, PI_COST, LINE_COST)
VALUES (1, 'Burger', 1, 5.99, 4.99);

INSERT INTO PRODUCT_ITEM (PI_ID, PI_NAME, PI_QUANTITY, PI_COST, LINE_COST)
VALUES (2, 'Coke', 2, 1.99, 1.99);



